import { z } from "zod";

const createJobZodSchema = z.object({
  body: z.object({
    title: z.string({ message: "Title is required" }),
    company: z.string().optional(),
    location: z.string({ message: "Location is required" }),
    type: z.string().optional(),
    salary: z.string().optional(),
    salaryMin: z.number().optional(),
    salaryMax: z.number().optional(),
    negotiable: z.boolean().optional(),
    logo: z.string().optional(),
    tags: z.array(z.string()).optional(),
    categoryId: z.string().optional(),
    subCategoryId: z.string().optional(),
    categoryName: z.string().optional(),
    shortDescription: z.string().optional(),
    description: z.string({ message: "Description is required" }),
    responsibilities: z.array(z.string()).optional(),
    requirements: z.array(z.string()).optional(),
    benefits: z.array(z.string()).optional(),
    education: z.string().optional(),
    experience: z.string().optional(),
    vacancy: z.number().optional(),
    deadline: z.string().optional(),
    jobNature: z.string().optional(),
    gender: z.string().optional(),
    ageRange: z.string().optional(),
    salaryReview: z.string().optional(),
    lunchFacility: z.string().optional(),
    festivalBonus: z.string().optional(),
    workingHours: z.string().optional(),
    weekend: z.string().optional(),
    address: z.string().optional(),
    website: z.string().optional(),
    email: z.string().optional(),
    phone: z.string().optional(),
    founded: z.string().optional(),
    companySize: z.string().optional(),
    industry: z.string().optional(),
    skills: z.array(z.string()).optional(),
    tools: z.array(z.string()).optional(),
    languages: z.array(z.string()).optional(),
    visaSponsorship: z.boolean().optional(),
    relocationAssistance: z.boolean().optional(),
    remotePolicy: z.string().optional(),
    department: z.string().optional(),
    reportingTo: z.string().optional(),
    teamSize: z.number().optional(),
    performanceBonus: z.boolean().optional(),
    healthInsurance: z.boolean().optional(),
    contactPerson: z.string().optional(),
    mapCoordinates: z.any().optional(),
    socialMedia: z.any().optional(),
    ceoName: z.string().optional(),
    applicationLink: z.string().optional(),
    internalId: z.string().optional(),
    referenceCode: z.string().optional(),
    keywords: z.array(z.string()).optional(),
    metaDescription: z.string().optional(),
    applicationDeadline: z.string().optional(),
    isUrgent: z.boolean().optional(),
    workStartTime: z.string().optional(),
    workTimeLimit: z.string().optional(),
    jobAmount: z.string().optional(),
    jobLocation: z.any().optional(),
  }),
});

const updateJobZodSchema = z.object({
  body: z.object({
    title: z.string().optional(),
    company: z.string().optional(),
    location: z.string().optional(),
    type: z.string().optional(),
    salary: z.string().optional(),
    salaryMin: z.number().optional(),
    salaryMax: z.number().optional(),
    negotiable: z.boolean().optional(),
    logo: z.string().optional(),
    tags: z.array(z.string()).optional(),
    categoryId: z.string().optional(),
    subCategoryId: z.string().optional(),
    categoryName: z.string().optional(),
    shortDescription: z.string().optional(),
    description: z.string().optional(),
    responsibilities: z.array(z.string()).optional(),
    requirements: z.array(z.string()).optional(),
    benefits: z.array(z.string()).optional(),
    education: z.string().optional(),
    experience: z.string().optional(),
    vacancy: z.number().optional(),
    deadline: z.string().optional(),
    jobNature: z.string().optional(),
    gender: z.string().optional(),
    ageRange: z.string().optional(),
    salaryReview: z.string().optional(),
    lunchFacility: z.string().optional(),
    festivalBonus: z.string().optional(),
    workingHours: z.string().optional(),
    weekend: z.string().optional(),
    address: z.string().optional(),
    website: z.string().optional(),
    email: z.string().optional(),
    phone: z.string().optional(),
    founded: z.string().optional(),
    companySize: z.string().optional(),
    industry: z.string().optional(),
    skills: z.array(z.string()).optional(),
    tools: z.array(z.string()).optional(),
    languages: z.array(z.string()).optional(),
    visaSponsorship: z.boolean().optional(),
    relocationAssistance: z.boolean().optional(),
    remotePolicy: z.string().optional(),
    department: z.string().optional(),
    reportingTo: z.string().optional(),
    teamSize: z.number().optional(),
    performanceBonus: z.boolean().optional(),
    healthInsurance: z.boolean().optional(),
    contactPerson: z.string().optional(),
    mapCoordinates: z.any().optional(),
    socialMedia: z.any().optional(),
    ceoName: z.string().optional(),
    applicationLink: z.string().optional(),
    internalId: z.string().optional(),
    referenceCode: z.string().optional(),
    keywords: z.array(z.string()).optional(),
    metaDescription: z.string().optional(),
    applicationDeadline: z.string().optional(),
    isUrgent: z.boolean().optional(),
    workStartTime: z.string().optional(),
    workTimeLimit: z.string().optional(),
    jobAmount: z.string().optional(),
    jobLocation: z.any().optional(),
    isPublished: z.boolean().optional(),
    status: z.boolean().optional(),
  }),
});

export const JobValidation = {
  createJobZodSchema,
  updateJobZodSchema,
};
