import { z } from "zod";

const createJobZodSchema = z.object({
  body: z.object({
    title: z.string({ message: "Title is required" }),
    company: z.string().optional().nullable(),
    location: z.string({ message: "Location is required" }),
    type: z.string().optional().nullable(),
    salary: z.string().optional().nullable(),
    salaryMin: z.number().optional().nullable(),
    salaryMax: z.number().optional().nullable(),
    negotiable: z.boolean().optional().nullable(),
    logo: z.string().optional().nullable(),
    thumbnailId: z.string().optional().nullable(),
    tags: z.array(z.string()).optional().nullable(),
    categoryId: z.string().optional().nullable(),
    subCategoryId: z.string().optional().nullable(),
    categoryName: z.string().optional().nullable(),
    shortDescription: z.string().optional().nullable(),
    description: z.string({ message: "Description is required" }),
    responsibilities: z.array(z.string()).optional().nullable(),
    requirements: z.array(z.string()).optional().nullable(),
    benefits: z.array(z.string()).optional().nullable(),
    education: z.string().optional().nullable(),
    experience: z.string().optional().nullable(),
    vacancy: z.number().optional().nullable(),
    deadline: z.string().optional().nullable(),
    jobNature: z.string().optional().nullable(),
    gender: z.string().optional().nullable(),
    ageRange: z.string().optional().nullable(),
    salaryReview: z.string().optional().nullable(),
    lunchFacility: z.string().optional().nullable(),
    festivalBonus: z.string().optional().nullable(),
    workingHours: z.string().optional().nullable(),
    weekend: z.string().optional().nullable(),
    address: z.string().optional().nullable(),
    website: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
    phone: z.string().optional().nullable(),
    founded: z.string().optional().nullable(),
    companySize: z.string().optional().nullable(),
    industry: z.string().optional().nullable(),
    skills: z.array(z.string()).optional().nullable(),
    tools: z.array(z.string()).optional().nullable(),
    languages: z.array(z.string()).optional().nullable(),
    visaSponsorship: z.boolean().optional().nullable(),
    relocationAssistance: z.boolean().optional().nullable(),
    remotePolicy: z.string().optional().nullable(),
    department: z.string().optional().nullable(),
    reportingTo: z.string().optional().nullable(),
    teamSize: z.number().optional().nullable(),
    performanceBonus: z.boolean().optional().nullable(),
    healthInsurance: z.boolean().optional().nullable(),
    contactPerson: z.string().optional().nullable(),
    mapCoordinates: z.any().optional().nullable(),
    socialMedia: z.any().optional().nullable(),
    ceoName: z.string().optional().nullable(),
    applicationLink: z.string().optional().nullable(),
    internalId: z.string().optional().nullable(),
    referenceCode: z.string().optional().nullable(),
    keywords: z.array(z.string()).optional().nullable(),
    metaDescription: z.string().optional().nullable(),
    applicationDeadline: z.string().optional().nullable(),
    isUrgent: z.boolean().optional().nullable(),
    workStartTime: z.string().optional().nullable(),
    workTimeLimit: z.string().optional().nullable(),
    jobAmount: z.string().optional().nullable(),
    jobLocation: z.any().optional().nullable(),
  }),
});

const updateJobZodSchema = z.object({
  body: z.object({
    title: z.string().optional().nullable(),
    company: z.string().optional().nullable(),
    location: z.string().optional().nullable(),
    type: z.string().optional().nullable(),
    salary: z.string().optional().nullable(),
    salaryMin: z.number().optional().nullable(),
    salaryMax: z.number().optional().nullable(),
    negotiable: z.boolean().optional().nullable(),
    logo: z.string().optional().nullable(),
    thumbnailId: z.string().optional().nullable(),
    tags: z.array(z.string()).optional().nullable(),
    categoryId: z.string().optional().nullable(),
    subCategoryId: z.string().optional().nullable(),
    categoryName: z.string().optional().nullable(),
    shortDescription: z.string().optional().nullable(),
    description: z.string().optional().nullable(),
    responsibilities: z.array(z.string()).optional().nullable(),
    requirements: z.array(z.string()).optional().nullable(),
    benefits: z.array(z.string()).optional().nullable(),
    education: z.string().optional().nullable(),
    experience: z.string().optional().nullable(),
    vacancy: z.number().optional().nullable(),
    deadline: z.string().optional().nullable(),
    jobNature: z.string().optional().nullable(),
    gender: z.string().optional().nullable(),
    ageRange: z.string().optional().nullable(),
    salaryReview: z.string().optional().nullable(),
    lunchFacility: z.string().optional().nullable(),
    festivalBonus: z.string().optional().nullable(),
    workingHours: z.string().optional().nullable(),
    weekend: z.string().optional().nullable(),
    address: z.string().optional().nullable(),
    website: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
    phone: z.string().optional().nullable(),
    founded: z.string().optional().nullable(),
    companySize: z.string().optional().nullable(),
    industry: z.string().optional().nullable(),
    skills: z.array(z.string()).optional().nullable(),
    tools: z.array(z.string()).optional().nullable(),
    languages: z.array(z.string()).optional().nullable(),
    visaSponsorship: z.boolean().optional().nullable(),
    relocationAssistance: z.boolean().optional().nullable(),
    remotePolicy: z.string().optional().nullable(),
    department: z.string().optional().nullable(),
    reportingTo: z.string().optional().nullable(),
    teamSize: z.number().optional().nullable(),
    performanceBonus: z.boolean().optional().nullable(),
    healthInsurance: z.boolean().optional().nullable(),
    contactPerson: z.string().optional().nullable(),
    mapCoordinates: z.any().optional().nullable(),
    socialMedia: z.any().optional().nullable(),
    ceoName: z.string().optional().nullable(),
    applicationLink: z.string().optional().nullable(),
    internalId: z.string().optional().nullable(),
    referenceCode: z.string().optional().nullable(),
    keywords: z.array(z.string()).optional().nullable(),
    metaDescription: z.string().optional().nullable(),
    applicationDeadline: z.string().optional().nullable(),
    isUrgent: z.boolean().optional().nullable(),
    workStartTime: z.string().optional().nullable(),
    workTimeLimit: z.string().optional().nullable(),
    jobAmount: z.string().optional().nullable(),
    jobLocation: z.any().optional().nullable(),
    isPublished: z.boolean().optional().nullable(),
    status: z.boolean().optional().nullable(),
  }),
});

export const JobValidation = {
  createJobZodSchema,
  updateJobZodSchema,
};
